### ISSUE TITLE
Print mode

### ISSUE THREAD

**Issue by iliak** [IronSummitMedia/startbootstrap-sb-admin-2#38]
Hello,

Is it possible to 'hide' the padding value of #page_wrapper in the print mode of bootstrap 'hidden-print' to use the full page width ? 

For example, in the blank.html file, remove all the theme and keep only what is inside '<div id="page-wrapper">' at line 371.

Thank you.

**Comment by davidtmiller** [comment]
If it's your personal preference then that is fine, go for it!
