### ISSUE TITLE
How to activate filtering in dataTables

### ISSUE THREAD

**Issue by fguilhaumon** [IronSummitMedia/startbootstrap-sb-admin-2#40]
Hope will not be kicked out for this, but how can I switch on the filtering/searching option in the first table (id="dataTables-example") on the page : 

startbootstrap-sb-admin-2/pages/tables.html

, or in all other tables ?

Finally how do I set up the tables options for datatable ? 

Thanks.

**Comment by challgren** [comment]
Here's some of my code that I've used to customize the data table. The following javascript has to be after the includes for the datatables.

```
$(document).ready(function() {
    $('#customer-table').dataTable({
        "sAjaxSource": "/admin/customers.json",
        "stateSave": true,
        "responsive": true,
        "bProcessing": true,
        "bServerSide": true,
        "lengthMenu": [[10, 25, 50, 100, 250, -1], [10, 25, 50, 100, 250, "All"]],
        "aoColumns": [
            {mData:"Customer.tradename"},
            {mData:"Customer.owner_name"},
            {mData:"Customer.location_address_full"},
            {mData:"Customer.permit_number"},
            {mData:"Customer.permit_expires"},
            {mData:"Customer.phone_number"},
            {mData:"Customer.credit_law", bSearchable: false}
        ],
        "createdRow": function( nRow, aData, iDisplayIndex ) {
            if (aData.Customer.credit_law) {
                $('td', nRow).addClass('danger');
            }
            $('td:eq(0)', nRow).html('<a href="/admin/customer/view/'+aData.Customer.id+'">'+aData.Customer.tradename+'</a>');
        }
    });

    $("#reset_state").click(function() {
        var table = $('#customer-table').DataTable();
        table.state.clear();
        window.location.reload();
    });
});
```

**Comment by challgren** [comment]
You can find examples at https://datatables.net/examples/index

**Comment by fguilhaumon** [comment]
thanks ! will check this out.

**Comment by fguilhaumon** [comment]
but the the "zero configuration" (https://datatables.net/examples/basic_init/zero_configuration.html) should produce a table with the search function enable by default.

My page (view-source:http://fguilhaumon.github.io/pages/tables.html) has this code after the includes for the datatables:

    <script>
    $(document).ready(function() {
        $('#example').DataTable({
        });
    });
    </script>

and the table "#example" is not showing the the search function : http://fguilhaumon.github.io/pages/tables.html

I don't get it ...

**Comment by challgren** [comment]
Your site isn't loading the datatables.min.js file needed

```
Failed to load resource: the server responded with a status of 404 (Not Found)
dataTables.bootstrap.min.js:5 Uncaught TypeError: Cannot read property 'defaults' of undefined
tables.html:1137 Uncaught TypeError: undefined is not a function
http://fguilhaumon.github.io/dist/images/back_2.gif Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by fguilhaumon** [comment]
ok I think I need to check things then. Thanks for the check.
