### ISSUE TITLE
bootstrap-datetimepicker does not diplay

### ISSUE THREAD

**Issue by Wayn0** [IronSummitMedia/startbootstrap-sb-admin-2#44]
Hi,

when using http://tarruda.github.io/bootstrap-datetimepicker/ with sb admin2  1.0.5 the date time picker pop up does not display. 

Using the inspector I can see that the html is generated, it's just never displayed.
No errors in console.

Please let me know if there is anything I can do, or test etc.

Thanks

**Comment by iRajul** [comment]
Replace open function with 

$scope.open = function() {
    console.log('calling open');
     $timeout( function(){
     $scope.status.opened = true; 
  }, 50);
    
  };

This works at my end

**Comment by Wayn0** [comment]
Thanks, I don't remember how I got around that but it was on an older project that I am no longer working on. but yeah thanks this will probably be very useful to others :-)

**Comment by bintangyoga** [comment]
same issue, where i should replace the code?
