### ISSUE TITLE
Can't fix with messenger, a bootstrap plugin.

### ISSUE THREAD

**Issue by x03570227** [IronSummitMedia/startbootstrap-sb-admin-2#50]
I have a problem with plugin messenger. when I use [Messenger](https://github.com/HubSpot/messenger) as my notify plugin, but when use it under sb-admin-2,  metisMenu erase all classes of messenger, I can't use any of messenger styles, and I can't control notify position.

Please fix it, thank you.

**Comment by challgren** [comment]
Sounds like an issue with metisMenu and Messenger, I'd suggest opening an issue with metisMenu and/or Messenger since this project only includes them from their repositories. metisMenu can be found at https://github.com/onokumus/metisMenu

**Comment by x03570227** [comment]
@challgren Thanks for your suggestion :)

I am trying resolve it, and I am finding and comparing other notify plugin.
