### ISSUE TITLE
Version was not updated in bower.json

### ISSUE THREAD

**Issue by SDKiller** [IronSummitMedia/startbootstrap-sb-admin-2#85]
Version `1.0.8` was tagged after https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/commit/afb82ee156913a9bc2274e578e94d4998ead5420

But it's still `1.0.7` in `bower.json`

https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/blob/gh-pages/bower.json#L3

**Comment by davidtmiller** [comment]
Thanks for that...got it updated!
